### ISSUE TITLE
Install problem (make -j all)

### ISSUE THREAD

**Issue by tbawin** [PacificBiosciences/FALCON-integrate#137]
Hi,

I am trying to install Falcon by the easy way.

When I enter the `make -j all` command, it comes with the following error message:

InstallationError: Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/bvlabo/Documents/FALCON-master/FALCON-integrate/pypeFLOW/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/bvlabo/Documents/FALCON-master/FALCON-integrate/pypeFLOW/
makefile:37: recipe for target 'install-pypeFLOW' failed
make[2]: *** [install-pypeFLOW] Error 1
make[2]: Leaving directory '/home/bvlabo/Documents/FALCON-master/FALCON-integrate/FALCON-make'
makefile:16: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/bvlabo/Documents/FALCON-master/FALCON-integrate/FALCON-make'
makefile:18: recipe for target 'all' failed
make: *** [all] Error 2

`cat env.sh` gives the following output:

FALCON_WORKSPACE=$(pwd)
PYTHONUSERBASE=$(pwd)/fc_env
FALCON_PREFIX=${PYTHONUSERBASE}
PATH=${PYTHONUSERBASE}/bin:${FALCON_PREFIX}/bin:${PATH}
export PYTHONUSERBASE
export FALCON_WORKSPACE
export FALCON_PREFIX
export PATH
mkdir -p ${FALCON_PREFIX}/include
mkdir -p ${FALCON_PREFIX}/bin
mkdir -p ${FALCON_PREFIX}/lib

And `git rev-parse HEAD`:

b51f7c367b928776c2ca8300a25127ecffb4ca26

I am not familiar with such installation process and a bit lost.

Do you have a suggestion to solve the problem?

**Comment by Xpangniu** [comment]
我也遇到这样的问题了，安装老不成功。Python的依赖包是不是安装的时候有冲突，谁知道这个软件到底该怎么装呀，我换了几个Linux系统都不行。

**Comment by pb-jchin** [comment]
@Xpangniu not sure what kind of Linux distribution you use. You need to be sure you have clear environment to start up.  For an example of installation, you can check an AWS image from this documentation https://speakerdeck.com/jchin/example-running-falcon-unzip-on-aws

**Comment by tbawin** [comment]
It seems that my problem was due to permissions regarding Python.

I finally installed pyenv (https://github.com/pyenv/pyenv#pyenv-shell) and Python 2.7.9. This avoids me to mess with the system's Python.

Then I tried again to install Falcon and it succeeded.

**Comment by Xpangniu** [comment]
Thanks very much。I reinstall the new system on my computer ，ubuntu 16.04 ，and Python 2.7.12。
 I tried again to install Falcon and it succeeded。but failed to make test ，the error message is so many。 
can you help me？PS：My English is not very good。 


------------------ 原始邮件 ------------------
发件人: "tbawin";<notifications@github.com>;
发送时间: 2017年4月14日(星期五) 晚上10:32
收件人: "PacificBiosciences/FALCON-integrate"<FALCON-integrate@noreply.github.com>; 
抄送: "糊涂不羊"<631949505@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [PacificBiosciences/FALCON-integrate] Install problem (make -jall) (#137)




It seems that my problem was due to permissions regarding Python.
 
I finally installed pyenv (https://github.com/pyenv/pyenv#pyenv-shell) and Python 2.7.9. This avoids me to mess with the system's Python.
 
Then I tried again to install Falcon and it succeeded.

**Comment by pb-cdunn** [comment]
> but failed to make test

If you post the errors from `make test`, we might be able to point you in the right direction. Please be sure to have the latest `master` branch of FALCON-integrate and up-to-date submodules.
