### ISSUE TITLE
show the version

### ISSUE THREAD

**Issue by dcopetti** [PacificBiosciences/FALCON-integrate#141]
Hi,
How can I display the version of the FALCON installation I am using?
Thanks,

**Comment by pb-jchin** [comment]
`git rev-parse HEAD` on the source repositories that you have cloned.

**Comment by dcopetti** [comment]
Thanks,
I get a long string of numbers and letters. But how does this translate to a number like 1.5, 2.2 or so? I am writing the methods for a paper.

**Comment by pb-jchin** [comment]
Hi, @dcopetti, different versioning systems use different ways to track.  As the FALCON/FALCON-Unzip is only still supported by the community rather than as a commercially backed product, it is best to follow Git's convention for the versioning information. The SHA-1 hash is pointing a unique point of the code base. We used SHA hashes in our paper too. If you think the whole SHA-1 is too long, you can use only the first 8 digits, e.g. using the output of   `git rev-parse --short`.

**Comment by dcopetti** [comment]
sounds good, will use that then.
Thanks!

**Comment by pb-cdunn** [comment]
Another option is to record a release tag from **FALCON-integrate**, the integration-package:

* https://github.com/PacificBiosciences/FALCON-integrate/releases
