### ISSUE TITLE
Wiki documentation does not sync with the v0.4.2

### ISSUE THREAD

**Issue by tiagoantao** [PacificBiosciences/FALCON-integrate#70]
I am trying to follow the documentation with the v0.4.2 tag (avoiding the `master` branch because I imagine that it is not stable). Namely https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation
It stops working at
`source env.sh`

I did find a `default-env.sh` on `master` and I using it to hack away. But currently the documentation for easy install does not work with the v0.4.2 tag

**Comment by pb-cdunn** [comment]
The wiki always corresponds to the `master` branch. You can find older versions of the wiki if you really want. We do not support old versions of the code. (We _do_ support old versions of the PacBio suite of tools, but not of these individual GitHub tools.) Please try `0.7.2`, or the latest "release".

Also, note that you are free to install dependencies however you choose. **FALCON-integrate/FALCON-make** is only one way of doing it. It's multi-language, so it's tricky. We recommend using `virtualenv`, but we no longer ship that with the tools since it does not work on all systems.
